-- =============================================================================
--  ITSM ticket database — PostgreSQL version of db/schema.sql
--
--  Same five tables, keys, CHECK lists and indexes as the SQLite schema, written for
--  PostgreSQL 14+. Differences from schema.sql:
--    * timestamps are TIMESTAMP (UTC) instead of TEXT, so date arithmetic uses
--      EXTRACT(EPOCH ...) / interval (see db/dialect.py, Postgres) instead of julianday()
--    * no STRICT / PRAGMA; foreign keys are always enforced
--    * IDENTITY columns instead of INTEGER PRIMARY KEY rowid aliases
--
--  Status (2026-09-30): written from the SQLite schema, NOT yet run against a live
--  PostgreSQL (none available in the build environment). The semantic catalog builder
--  and the API compose their date fragments through db/dialect.py, so pointing them at
--  PostgreSQL needs: DB_DIALECT=postgres, a PostgreSQL connection factory in place of
--  nl2sql.connect_readonly (a read-only role + statement_timeout replace the SQLite
--  authorizer and progress handler) and the meta_* tables created here as well.
-- =============================================================================

DROP TABLE IF EXISTS changes;
DROP TABLE IF EXISTS incidents;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS sla_targets;
DROP TABLE IF EXISTS assignment_groups;

CREATE TABLE assignment_groups (
    id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  TEXT    NOT NULL UNIQUE
);

CREATE TABLE users (
    id                   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                 TEXT    NOT NULL,
    role                 TEXT    NOT NULL
                         CHECK (role IN ('agent', 'team_lead', 'manager', 'admin')),
    assignment_group_id  INTEGER REFERENCES assignment_groups (id)
);
CREATE INDEX idx_users_group ON users (assignment_group_id);

CREATE TABLE sla_targets (
    priority        INTEGER PRIMARY KEY CHECK (priority BETWEEN 1 AND 4),
    target_minutes  INTEGER NOT NULL CHECK (target_minutes > 0)
);

CREATE TABLE incidents (
    id                   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    short_desc           TEXT      NOT NULL,
    priority             INTEGER   NOT NULL REFERENCES sla_targets (priority),
    status               TEXT      NOT NULL
                         CHECK (status IN ('New', 'In Progress', 'On Hold',
                                           'Resolved', 'Closed', 'Cancelled')),
    assignment_group_id  INTEGER   NOT NULL REFERENCES assignment_groups (id),
    opened_at            TIMESTAMP NOT NULL,
    resolved_at          TIMESTAMP,
    reopened_count       INTEGER   NOT NULL DEFAULT 0 CHECK (reopened_count >= 0),
    CHECK (resolved_at IS NULL OR resolved_at >= opened_at),
    CHECK ((status IN ('Resolved', 'Closed')) = (resolved_at IS NOT NULL))
);
CREATE INDEX idx_incidents_group_opened ON incidents (assignment_group_id, opened_at);
CREATE INDEX idx_incidents_opened       ON incidents (opened_at);
CREATE INDEX idx_incidents_priority     ON incidents (priority);
CREATE INDEX idx_incidents_status       ON incidents (status);

CREATE TABLE changes (
    id                   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description          TEXT      NOT NULL,
    risk                 TEXT      NOT NULL CHECK (risk IN ('Low', 'Moderate', 'High')),
    status               TEXT      NOT NULL
                         CHECK (status IN ('Draft', 'Assess', 'Scheduled',
                                           'Implement', 'Review', 'Closed', 'Cancelled')),
    assignment_group_id  INTEGER   NOT NULL REFERENCES assignment_groups (id),
    planned_start        TIMESTAMP NOT NULL,
    planned_end          TIMESTAMP NOT NULL,
    CHECK (planned_end >= planned_start)
);
CREATE INDEX idx_changes_group_start ON changes (assignment_group_id, planned_start);
CREATE INDEX idx_changes_start       ON changes (planned_start);
CREATE INDEX idx_changes_status      ON changes (status);
